### ISSUE TITLE
dominik asked for data 

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#99] opened 2016-07-18 15:59 UTC
Hi Mohammad, I'd like to ask you if you could add multiple lines to the stop in your database model. I mean something like this: http://pastebin.com/WPaypNXX. This would help our group to demonstrate the different lines on the stop list page.. But don't worry, this is not urgent..

**Comment by mzeen** [comment] 2016-07-20 12:09
The link you mentioned in the issue is no longer working and we are not supposed to change the database model as we don't have much time to do any changes at the end time. Now closing this issue.

**Closed as completed by mzeen** 2016-07-20 12:09 UTC
