### ISSUE TITLE
documenting how to set up server

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#45] opened 2016-05-30 17:27 UTC
@Sriramk88 @bonkilejay the readme file should be updated with correct instruction.
step by step guide and requirements for setting up the server should be stated. 
if it's too much create a wiki page for it

**Comment by skaldo** [comment] 2016-06-02 06:20
I just want to point out, that we want need this guide to perform the integration testing. @mbaniasad wanted to fix the date for the integration testing, I just want to state that we can begin with the integration testing as soon as you provide us the guide how to start the server.

@mmueller301 & @themetalone, please follow this issue.

**Comment by mbaniasad** [comment] 2016-06-02 09:49
@bonkilejay please provide the server start instruction for the client groups as soon as possible.

**Comment by mbaniasad** [comment] 2016-06-02 09:56
@skaldo since setting up the server in your system is not an very easy task to do .
I would say for the integration test meeting you dont need a local running version of the server. and we can do it side by side. so if any change is required it could be done and deployed fast

**Comment by skaldo** [comment] 2016-06-02 10:06
@mbaniasad, I can't believe that the deployment on other machine is so hard. Based on [this](https://github.com/oasp/oasp4j/wiki/oasp-Deploy-&-Run-OASP-locally) it's matter of one or two commands. I can provide Linux, OS X, or Windows with all required prerequisites installed.

**Comment by mbaniasad** [comment] 2016-06-02 12:45
we have to do the integration test together so if there is a problem we can fix it at the same time and do a retest

**Comment by skaldo** [comment] 2016-06-02 18:34
@mbaniasad I see that the guide is available. Thank you for it.
Regarding on-site integration test I'm not sure if any of our team's members is going to be available.

It is important to have a documentation of the integration tests, for this reason a release of you software is needed. If there are going to be any issues found during the testing, these should be documented in the release notes and as bugs. It doesn't matter, that the issue is going to be fixed on the same day, the improvement should be documented.
Do you have a release of the server against which you want to perform the integration tests? Please upload it to GitHub as release (#36).

**Comment by skaldo** [comment] 2016-06-03 17:24
I was able to successfully install the server on my VPS. Thanks for the guide!
It's a pity that this haven't been available some weeks ago. After you'll add #54, I think you can close this issue! :tada:

**Comment by ChristianAGSE** [comment] 2016-06-07 12:18
Everything done in here.

**Closed as completed by ChristianAGSE** 2016-06-07 12:18 UTC
